apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart 
    project: roboshop
    tier: app
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"  
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart 
    project: roboshop
    tier: app
spec:
# no of replicas needed
  replicas: 1
  selector:
    matchLabels:
  # these are the labels replica set uses to create pod replicas, this should match pod replicas
      component: cart 
      project: roboshop
      tier: app
    # this is pod defination
  template:
    metadata:
      labels:
        component: cart 
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: bhargav9968/cart:v1
        envFrom:
        - configMapRef:
            name: cart


---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart 
    project: roboshop
    tier: app   
spec:
  selector:
    component: cart 
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port(cart container)