apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping 
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080" 
  DB_HOST: "mysql"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping 
    project: roboshop
    tier: app
spec:
# no of replicas needed
  replicas: 1
  selector:
    matchLabels:
  # these are the labels replica set uses to create pod replicas, this should match pod replicas
      component: shipping 
      project: roboshop
      tier: app
    # this is pod defination
  template:
    metadata:
      labels:
        component: shipping 
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: bhargav9968/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping


---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping 
    project: roboshop
    tier: app   
spec:
  selector:
    component: shipping 
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port(shipping container)