apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq 
    project: roboshop
    tier: database
type: Opaque    
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq 
    project: roboshop
    tier: database
spec:
# no of replicas needed
  replicas: 1
  selector:
    matchLabels:
  # these are the labels replica set uses to create pod replicas, this should match pod replicas
      component: rabbitmq 
      project: roboshop
      tier: database
    # this is pod defination
  template:
    metadata:
      labels:
        component: rabbitmq 
        project: roboshop
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
          - secretRef:
              name: rabbitmq
             
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq 
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq 
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port(mongodb container)        
          