apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb 
    project: roboshop
    tier: database
spec:
# no of replicas needed
  replicas: 1
  selector:
    matchLabels:
  # these are the labels replica set uses to create pod replicas, this should match pod replicas
      component: mongodb 
      project: roboshop
      tier: database
    # this is pod defination
  template:
    metadata:
      labels:
        component: mongodb 
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: bhargav9968/mongodb:v1   
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    component: mongodb 
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb 
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port(nginx container)        
          