apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue 
    project: roboshop
    tier: app
data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue 
    project: roboshop
    tier: app
spec:
# no of replicas needed
  replicas: 1
  selector:
    matchLabels:
  # these are the labels replica set uses to create pod replicas, this should match pod replicas
      component: catalogue 
      project: roboshop
      tier: app
    # this is pod defination
  template:
    metadata:
      labels:
        component: catalogue 
        project: roboshop
        tier: app
    spec:
      containers:
      - name: mongodb
        image: bhargav9968/catalogue:v1
        envFrom:
        - configMapRef:
            name: catalogue


---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue 
    project: roboshop
    tier: app   
spec:
  selector:
    component: catalogue 
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port(nginx container)