apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
# no of replicas needed
  replicas: 1
  selector:
    matchLabels:
  # these are the labels replica set uses to create pod replicas, this should match pod replicas
      component: redis
      project: roboshop
      tier: database
    # this is pod defination
  template:
    metadata:
      labels:
        component: redis 
        project: roboshop
        tier: database
    spec:
      containers:
      - name: redis
        image: redis:7.0   
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    component: redis 
    project: roboshop
    tier: database
spec:
  selector:
    component: redis 
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # container port(redis container)        
          